CREATE TABLE IF NOT EXISTS stg_receipts_items (
    receipt_id TEXT,
    barcode TEXT,
    description TEXT,
    final_price NUMERIC(9, 2),
    item_price NUMERIC(9, 2),
    needs_fetch_review BOOLEAN,
    partner_item_id TEXT,
    prevent_target_gap_points BOOLEAN,
    quantity_purchased INTEGER,
    user_flagged_barcode TEXT,
    user_flagged_new_item BOOLEAN,
    user_flagged_price NUMERIC(9, 2),
    user_flagged_quantity INTEGER,
    needs_fetch_review_reason TEXT,
    points_not_awarded_reason TEXT,
    points_payer_id TEXT,
    rewards_group TEXT,
    rewards_product_partner_id TEXT,
    user_flagged_description TEXT,
    original_meta_brite_barcode TEXT,
    original_meta_brite_description TEXT,
    brand_code TEXT,
    competitor_rewards_group TEXT,
    discounted_item_price NUMERIC(9, 2),
    original_receipt_item_text TEXT,
    item_number TEXT,
    original_meta_brite_quantity_purchased INTEGER,
    points_earned NUMERIC(15, 2),
    target_price NUMERIC(9, 2),
    competitive_product BOOLEAN,
    original_final_price NUMERIC(9, 2),
    original_meta_brite_item_price NUMERIC(9, 2),
    deleted BOOLEAN,
    price_after_coupon NUMERIC(9, 2),
    metabrite_campaign_id TEXT
);

